# Site
title:              Physicist and Engineer
bio:                'This product was designed with the intent of being a versatile, high-performance worker, capable of understanding all systems involved in an engineering task down from the atomic level up to the turbopump. Not only is it capable of adapting with ease to any task but it is specially suited for systems conception and design, for innovation, having an intimate view of all the different parts, how they fit together and harness the power of physics to achieve their intended purpose.
Though it comes with pre-installed cutting-edge software running on state-of-the-art hardware, taking it to its full potential will require practical experience which it is actively looking for. Prior tests show it has a very high specific impulse and can take extreme work loads.
'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Los Angeles, CA
phone:              310-318-5555
email:              info@default.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
